version: '3.8'

services: 
    db: 
        image: postgres
        env_file: .env
        restart: 'always'
        volumes:
            - db_volume:/var/lib/postgresql/data
    keycloak:
        image: scalingo/scalingo-18
        volumes: 
            - .:/buildpack
        env_file: .env
        depends_on:
            - db
volumes: 
    db_volume:
